server:
  port: 8080
  servlet:
    context-path: /auth

# db
spring:
  application:
    name: auth-service
  datasource:
    url: "jdbc:mysql://${AUTH_DB_HOST}:${AUTH_DB_PORT}/${AUTH_MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${AUTH_MYSQL_USER}
    password: ${AUTH_MYSQL_PASSWORD}
  # flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: "jdbc:mysql://${AUTH_DB_HOST}:${AUTH_DB_PORT}/${AUTH_MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh"
    user: ${AUTH_MYSQL_USER}
    password: ${AUTH_MYSQL_PASSWORD}
    baseline-on-migrate: true
    out-of-order: true
    clean-disabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

# jwt
jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS}
  refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS}

# redis
microservice-redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  timeout: ${REDIS_TIMEOUT}
  database: ${REDIS_DATABASE}


# logging
logging:
  level:
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security.web: DEBUG
    org.springframework.security: DEBUG
