name: microservice

x-redis-common: &redis-common
  image: ${REDIS_IMAGE}
  command: >
    redis-server
    --cluster-enabled ${REDIS_CLUSTER_ENABLED}
    --cluster-config-file ${REDIS_CLUSTER_CONFIG_FILE}
    --cluster-node-timeout ${REDIS_CLUSTER_TIMEOUT}
    --appendonly ${REDIS_APPENDONLY}
  restart: always


x-kafka-env: &kafka-env
  KAFKA_PROCESS_ROLES: broker,controller
  KAFKA_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
  KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:19092,2@kafka-2:19093,3@kafka-3:19094
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_LOG_DIRS: /var/lib/kafka/data
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

x-kafka-common: &kafka-common
  image: ${KAFKA_IMAGE}
  restart: always

services:
  redis-node-1:
    <<: *redis-common
    container_name: redis-node-1
    ports:
      - "${REDIS_NODE_1_PORT}:6379"

  redis-node-2:
    <<: *redis-common
    container_name: redis-node-2
    ports:
      - "${REDIS_NODE_2_PORT}:6379"

  redis-node-3:
    <<: *redis-common
    container_name: redis-node-3
    ports:
      - "${REDIS_NODE_3_PORT}:6379"

  redis-node-4:
    <<: *redis-common
    container_name: redis-node-4
    ports:
      - "${REDIS_NODE_4_PORT}:6379"

  redis-node-5:
    <<: *redis-common
    container_name: redis-node-5
    ports:
      - "${REDIS_NODE_5_PORT}:6379"

  redis-node-6:
    <<: *redis-common
    container_name: redis-node-6
    ports:
      - "${REDIS_NODE_6_PORT}:6379"

  redis-cluster-init:
    image: ${REDIS_IMAGE}
    container_name: redis-cluster-init
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    entrypoint: >
      sh -c "
      echo '⏳ Waiting for Redis nodes...';
      sleep ${REDIS_INIT_SLEEP};

      echo '🚀 Creating Redis Cluster...';

      redis-cli --cluster create \
      redis-node-1:6379 \
      redis-node-2:6379 \
      redis-node-3:6379 \
      redis-node-4:6379 \
      redis-node-5:6379 \
      redis-node-6:6379 \
      --cluster-replicas ${REDIS_CLUSTER_REPLICAS} \
      --cluster-yes;

      echo '✅ Redis Cluster ready!';
      "


  # kafka
  kafka-1:
    <<: *kafka-common
    container_name: kafka-1
    ports:
      - "${KAFKA_PORT_1}:9092"
    volumes:
      - kafka1-data:/var/lib/kafka/data
    environment:
      <<: *kafka-env
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092

  kafka-2:
    <<: *kafka-common
    container_name: kafka-2
    ports:
      - "${KAFKA_PORT_2}:9092"
    volumes:
      - kafka2-data:/var/lib/kafka/data
    environment:
      <<: *kafka-env
      KAFKA_NODE_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:19093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092

  kafka-3:
    <<: *kafka-common
    container_name: kafka-3
    ports:
      - "${KAFKA_PORT_3}:9092"
    volumes:
      - kafka3-data:/var/lib/kafka/data
    environment:
      <<: *kafka-env
      KAFKA_NODE_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:19094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092

  schema-registry:
    image: ${SCHEMA_REGISTRY_IMAGE}
    container_name: schema-registry
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - "${SCHEMA_REGISTRY_PORT}:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  kafka-ui:
    image: ${KAFKA_UI_IMAGE}
    container_name: kafka-ui
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kraft
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081


volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data: