name: microservice

services:

  # Authentication db
  mysql:
    image: mysql:8.0
    container_name: auth
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTH_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${AUTH_MYSQL_DATABASE}
      MYSQL_USER: ${AUTH_MYSQL_USER}
      MYSQL_PASSWORD: ${AUTH_MYSQL_PASSWORD}
    ports:
      - "${AUTH_DB_PORT}:3306"

  # Redis
  redis:
    image: redis:7.0
    container_name: microservice-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env

