server:
  port: ${PROFILE_SERVICE_PORT}
  servlet:
    context-path: /${PROFILE_SERVICE_PATH}

# db
spring:
  neo4j:
    uri: bolt://${PROFILE_NEO4J_HOST}:${PROFILE_NEO4J_PORT}
    authentication:
      username: ${PROFILE_NEO4J_USERNAME}
      password: ${PROFILE_NEO4J_PASSWORD}


# redis
microservice-redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  timeout: ${REDIS_TIMEOUT}
  database: ${PROFILE_DATABASE}